### ISSUE TITLE
Why you are not using `create-react`  cli tool in your book?

### ISSUE THREAD

**Issue by malikasinger1** [azat-co/react-quickly#7]
#Why you are not using `create-react`  cli tool in your book?

**Comment by azat-co** [comment]
@malikasinger1 why should I use it in my book? 

the best way to understand what is happening is to create everything from scratch, not to rely on some tool which will disappear or be broken in a few weeks. if you won't to use the tool, just read its documentation... the book teaches you fundamentals not some magic from code generators which add bunch of stuff which no one knows how works.

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md
https://github.com/facebookincubator/create-react-app#getting-started
